#!/usr/bin/perl

use strict;
use lib "../lib";
use Aztec;
use CGI;

my $Query = CGI->new();
my $Params = $Query->Vars();

Aztec::PrintHeader();
Aztec::PrintAztecSquareGrid( { az => $Params->{'az'} } );
Aztec::PrintAztecSquareDimers( { dimers => $Params->{'json'} } );
Aztec::PrintEndAztecSquareGrid();

use Data::Dumper;print "<pre>" . Dumper( $Params ) . "</pre>";
Aztec::PrintFooter();

1;
